services:
  web:
    image: php:8.2-fpm
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: poseidon
      MYSQL_DATABASE: DP-PRJ
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./web:/var/www/html
    ports:
      - 80:80

volumes:
  db_data:
